import type { GameDef } from './types'

/**
 * 차시별 발표자 뽑기 게임 18종.
 *
 * 엔진은 전부 같다. 1강 사다리 코드(`src/lib/ladder.ts`)의
 * 씨앗 재현성·전단사·비상 추첨을 그대로 쓰고, 화면 표현만 mode 로 갈린다.
 *
 * 규칙 (지시서 10.1)
 *  - 실행은 강사만. 시드는 서버가 만든다.
 *  - 정답·오답을 기준으로 뽑지 않는다. 틀린 답을 고른 사람을 지목하는 데 쓰지 않는다.
 *  - 발표 횟수가 적은 사람의 확률을 높인다(기본 켬).
 *  - prefers-reduced-motion 이면 애니메이션을 건너뛰고 결과를 즉시 보여준다.
 */
export const GAMES: GameDef[] = [
  {
    id: '01-auction',
    lessonId: '01',
    mode: 'ladder',
    tab: '사다리타기',
    lead: '같은 수업을 두고도 무엇이 가장 중요한지는 갈립니다.\n두 분의 이유를 직접 들어보겠습니다.',
    hint: '자리를 하나 고르세요. 강사가 결과를 열면 사다리를 타고 내려갑니다.',
    choiceField: 'allocation',
    reasonField: 'defense',
    askLine: '우리 모둠이 그 카드에 가장 많이 준 이유를 말해 주세요.',
    presenterAsk: '두 분의 이유가 어디에서 갈리는지 학급이 듣게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '02-sealed-envelope',
    lessonId: '02',
    mode: 'sealed-envelope',
    tab: '봉인된 증거 봉투',
    lead: '봉투 하나에 발표 표시가 들어 있습니다.\n열기 전에 "내가 걸릴 확률"을 먼저 적어 주세요.',
    hint: '연 뒤에는 예상과 결과의 차이를 한 줄로 적습니다.',
    choiceField: 'observationVsInference',
    reasonField: 'reason',
    askLine: '어떤 문장을 관찰로, 어떤 문장을 추론으로 갈랐는지 그 기준을 말해 주세요.',
    presenterAsk: '확률 예상과 실제 결과의 차이를 과학의 본성과 연결한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '03-card-flip',
    lessonId: '03',
    mode: 'card-flip',
    tab: '학생 발화 카드 뒤집기',
    lead: '카드 앞면에는 중학생의 말이 적혀 있습니다.\n한 장 뒤에 발표 표시가 있습니다.',
    hint: '카드를 고르면 그 발화가 먼저 보이고, 그다음에 표시가 열립니다.',
    choiceField: 'diagnosis',
    reasonField: 'followUpQuestion',
    askLine: '그 발화 뒤에 있는 학생의 사고모형을 진단해 주세요.',
    presenterAsk: '같은 발화에 서로 다른 진단이 나오는지 확인한다.',
    candidateRule: 'byResponseType',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '04-scaffold-stairs',
    lessonId: '04',
    mode: 'scaffold-stairs',
    tab: '비계 계단',
    lead: '말이 계단을 오르다 무작위 칸에서 멈춥니다.\n멈춘 칸이 지금 학생에게 준 도움의 수준입니다.',
    hint: '계단 칸마다 도움의 세기가 다릅니다.',
    choiceField: 'hintLevel',
    reasonField: 'reason',
    askLine: '이 도움을 언제, 어떤 증거를 보고 줄일 것인지 말해 주세요.',
    presenterAsk: '도움의 양이 아니라 제거 시점을 이야기하게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '05-survival',
    lessonId: '05',
    mode: 'survival',
    tab: '설명 생존',
    lead: '증거가 한 장씩 공개될 때마다 후보가 한 명씩 빠집니다.\n마지막까지 남은 한 분이 발표합니다.',
    hint: '오래 버틴 설명이 아니라 증거에 맞게 고친 설명을 봅니다.',
    choiceField: 'explanationChoice',
    reasonField: 'changedReason',
    askLine: '어떤 증거에서 설명을 바꿨는지, 무엇을 그대로 두었는지 말해 주세요.',
    presenterAsk: '수정 자체가 실패가 아니라는 점을 학급에 짚는다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 1,
  },
  {
    id: '06-map-pin',
    lessonId: '06',
    mode: 'map-pin',
    tab: '교육과정 지도 핀',
    lead: '영역 지도 위에서 핀이 돌다 멈춥니다.\n멈춘 영역의 성취기준을 해부합니다.',
    hint: '핀이 멈춘 영역을 맡은 분이 발표합니다.',
    choiceField: 'domain',
    reasonField: 'threeCategories',
    askLine: '그 영역 성취기준의 세 범주(지식·이해 / 과정·기능 / 가치·태도)를 갈라 주세요.',
    presenterAsk: '성취기준 문장에서 근거 구절을 직접 짚게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '07-triple-spinner',
    lessonId: '07',
    mode: 'triple-spinner',
    tab: '목표·증거·활동 스피너',
    lead: '세 칸 룰렛이 돕니다.\n멈춘 칸이 여러분 설계에서 다시 볼 자리입니다.',
    hint: '목표 / 증거 / 활동 중 어느 칸에 멈추는지 봅니다.',
    choiceField: 'alignment',
    reasonField: 'misfit',
    askLine: '멈춘 칸에서 내 설계가 어긋난 곳을 짚어 주세요.',
    presenterAsk: '활동목표와 학습목표를 섞어 쓴 자리를 찾게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '08-variable-dice',
    lessonId: '08',
    mode: 'variable-dice',
    tab: '변인 주사위',
    lead: '주사위 두 개가 굴러갑니다.\n변인 하나와 조건 하나가 짝지어집니다.',
    hint: '나온 조합으로 공정한 비교를 설계합니다.',
    choiceField: 'design',
    reasonField: 'controlReason',
    askLine: '그 조합에서 무엇을 같게 두어야 공정한 비교가 되는지 말해 주세요.',
    presenterAsk: '통제 목록 암송이 아니라 통제가 주장을 어떻게 정당화하는지 묻는다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '09-bracket',
    lessonId: '09',
    mode: 'bracket',
    tab: '모형 대진 추첨',
    lead: '무작위 대진표가 모형 두 개를 맞붙입니다.\n어느 모형이 더 넓게 설명하는지 봅니다.',
    hint: '이기는 모형을 뽑는 게임이 아닙니다. 설명 범위를 비교합니다.',
    choiceField: 'modelSketch',
    reasonField: 'scope',
    askLine: '두 모형의 설명 범위가 어디에서 갈리는지 말해 주세요.',
    presenterAsk: '예쁜 그림이 아니라 요소 사이의 인과 관계를 보게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '10-draft-order',
    lessonId: '10',
    mode: 'draft-order',
    tab: '드래프트 순번',
    lead: '추첨 순번대로 수업 상황 카드를 고릅니다.\n마지막 순번이 먼저 발표합니다.',
    hint: '남은 카드가 적을수록 선택의 제약이 커집니다. 그 제약이 오늘의 주제입니다.',
    choiceField: 'modelChoice',
    reasonField: 'reason',
    askLine: '이 상황에 그 모형을 고른 이유를 말해 주세요.',
    presenterAsk: '다른 모둠이 반례 조건을 제시하게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '11-representation-roulette',
    lessonId: '11',
    mode: 'representation-roulette',
    tab: '표상 룰렛',
    lead: '현상 / 입자 그림 / 그래프 / 수식 네 칸이 돕니다.\n멈춘 표상으로 번역합니다.',
    hint: '번역한 뒤 "사라진 정보"를 함께 말합니다.',
    choiceField: 'translation',
    reasonField: 'lostInformation',
    askLine: '멈춘 표상으로 번역하고, 그 과정에서 사라진 정보를 말해 주세요.',
    presenterAsk: '새 표상에서 더 잘 보이는 것과 사라지는 것을 둘 다 묻는다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '12-jury-roles',
    lessonId: '12',
    mode: 'jury-roles',
    tab: '배심원 역할 추첨',
    lead: '주장자·반론자·증거 검토자·요약자를 동시에 뽑습니다.\n네 분이 한 장면을 함께 만듭니다.',
    hint: '역할은 정답 발표자가 아니라 담화 이동입니다.',
    choiceField: 'claim',
    reasonField: 'evidence',
    askLine: '맡은 역할의 담화 이동을 실제로 해 주세요.',
    presenterAsk: '결론만 듣지 말고 증거와 추론에 응답하게 한다.',
    candidateRule: 'splitOpinion',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 4,
  },
  {
    id: '13-stakeholder-lots',
    lessonId: '13',
    mode: 'stakeholder-lots',
    tab: '이해당사자 제비',
    lead: '연구자·주민·기업·지자체·학생 역할 카드를 나눕니다.\n뽑힌 분이 그 입장에서 말합니다.',
    hint: '찬반이 아니라 기준과 우려를 말합니다.',
    choiceField: 'decision',
    reasonField: 'criteria',
    askLine: '그 입장이 중요하게 보는 기준과 우려를 말해 주세요.',
    presenterAsk: '사실 판단과 가치 판단을 갈라서 듣게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '14-silent-data',
    lessonId: '14',
    mode: 'silent-data',
    tab: '침묵 데이터',
    lead: '이번 추첨은 발표 기회가 적었던 분의 확률을 크게 줍니다.\n가중치를 화면에 그대로 공개합니다.',
    hint: '규칙 자체가 오늘의 학습 내용입니다. 숨기지 않습니다.',
    choiceField: 'contributionType',
    reasonField: 'reason',
    askLine: '우리 모둠에서 누구의 생각이 기록에 남았는지 말해 주세요.',
    presenterAsk: '가중치 표를 띄운 채로 진행한다. 규칙을 숨기지 않는다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: true,
    winnerCount: 2,
  },
  {
    id: '15-by-response-type',
    lessonId: '15',
    mode: 'by-response-type',
    tab: '응답 유형별 한 명',
    lead: '형성평가 응답이 유형별로 묶였습니다.\n묶음마다 한 분씩 뽑습니다.',
    hint: '정답 여부가 아니라 이유의 유형으로 묶습니다.',
    choiceField: 'answer',
    reasonField: 'reason',
    askLine: '같은 답을 고른 사람들의 서로 다른 이유를 말해 주세요.',
    presenterAsk: '같은 답 안의 다른 이유가 드러나면 다음 행동이 달라진다.',
    candidateRule: 'byResponseType',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 3,
  },
  {
    id: '16-boundary-pair',
    lessonId: '16',
    mode: 'boundary-pair',
    tab: '경계 사례 짝',
    lead: '같은 산출물에 다른 점수를 준 두 분을 짝으로 뽑습니다.\n점수가 아니라 기준 문구를 봅니다.',
    hint: '누가 맞았는지 가리지 않습니다.',
    choiceField: 'score',
    reasonField: 'criterionQuote',
    askLine: '기준 문구의 어느 말에서 판단이 갈렸는지 말해 주세요.',
    presenterAsk: '루브릭 문장을 늘리지 말고 모호한 말을 찾아 고치게 한다.',
    candidateRule: 'splitOpinion',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 2,
  },
  {
    id: '17-sentence-audit',
    lessonId: '17',
    mode: 'sentence-audit',
    tab: '문장 감사 배정',
    lead: 'AI 응답의 문장에 번호가 붙었습니다.\n무작위로 배정된 문장을 맡습니다.',
    hint: '맡은 문장만 판정하면 됩니다.',
    choiceField: 'sentenceVerdict',
    reasonField: 'sourceNeeded',
    askLine: '맡은 문장이 사실인지, 해석인지, 출처가 필요한지, 오류인지 판정해 주세요.',
    presenterAsk: 'AI가 유창하다는 이유로 타당성을 인정하지 않게 한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: false,
    winnerCount: 3,
  },
  {
    id: '18-reteach-order',
    lessonId: '18',
    mode: 'reteach-order',
    tab: '재수업 순번',
    lead: '마이크로티칭 순서를 뽑습니다.\n1강 사다리에서 이미 발표한 분은 후보에서 빠집니다.',
    hint: '한 학기 동안 한 번도 발표하지 않은 분이 먼저 옵니다.',
    choiceField: 'reteachPlan',
    reasonField: 'evidenceOfChange',
    askLine: '수정 전후 학생 반응의 차이를 증거로 말해 주세요.',
    presenterAsk: '1강 결과와 겹치는 사람을 제외했음을 화면에 표시한다.',
    candidateRule: 'all',
    weightByFewPresentations: true,
    revealWeights: true,
    winnerCount: 2,
  },
]

export const GAMES_BY_LESSON = Object.fromEntries(GAMES.map((g) => [g.lessonId, g])) as Record<
  string,
  GameDef
>

export function gameById(id: string): GameDef | undefined {
  return GAMES.find((g) => g.id === id)
}
